buildingdepot/CentralService/app/central/forms.py
"""
CentralService.form
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Contains the definitions for all the forms that will be shown to the user
in the frontend of the CentralService such as the form to create new buildings,
tags,dataserivces etc.

@copyright: (c) 2024 SynergyLabs
@license: CMU License. See License file for details.
"""

from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SelectMultipleField,
    SubmitField,
    SelectField,
    BooleanField,
)
from wtforms.validators import DataRequired


class TagTypeForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    description = StringField("Description")
    parents = SelectMultipleField("Parents")
    submit = SubmitField("Submit")


class BuildingTemplateForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    description = StringField("Description")
    tag_types = SelectMultipleField("Tag types")
    submit = SubmitField("Submit")


class BuildingForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    description = StringField("Description")
    template = SelectField("Template", validators=[DataRequired()])
    submit = SubmitField("Submit")


class RoleForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    description = StringField("Description")
    permission = SelectField(
        "Permission", choices=[("r", "r"), ("r/w", "r/w")], validators=[DataRequired()]
    )
    type = SelectField(
        "Type",
        choices=[("default", "default"), ("local", "local"), ("super", "super")],
        validators=[DataRequired()],
    )
    submit = SubmitField("Submit")


class DataServiceForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    description = StringField("Description")
    host = StringField("Host", validators=[DataRequired()])
    port = StringField("Port", validators=[DataRequired()])
    submit = SubmitField("Submit")


class SensorForm(FlaskForm):
    source_name = StringField("Source Name")
    source_identifier = StringField("Source Identifier")
    building = SelectField("Building", validators=[DataRequired()])
    submit = SubmitField("Submit")


class SensorGroupForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    description = StringField("Description")
    building = SelectField("Building", validators=[DataRequired()])
    submit = SubmitField("Submit")


class UserGroupForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    description = StringField("Description")
    submit = SubmitField("Submit")


class PermissionForm(FlaskForm):
    user_group = SelectField("User Group", validators=[DataRequired()])
    sensor_group = SelectField("Sensor Group", validators=[DataRequired()])
    permission = SelectField(
        "Building",
        choices=[("r", "r"), ("r/w", "r/w"), ("d/r", "d/r"), ("r/w/p", "r/w/p")],
        validators=[DataRequired()],
    )
    submit = SubmitField("Submit")


class PermissionQueryForm(FlaskForm):
    user = StringField("User Email", validators=[DataRequired()])
    sensor = StringField("Sensor ID", validators=[DataRequired()])
    submit = SubmitField("Submit")

buildingdepot/CentralService/app/central/__init__.py
from flask import Blueprint

central = Blueprint("central", __name__)

from . import views

buildingdepot/CentralService/app/central/views.py
"""
CentalService.central.views
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Contains all the definitions for the CentralService frontend functions.
Any action on the Web interface will generate a call to one of these
functions that renders a html page.

For example opening up http://localhost:81/central/tagtype on your installation
of BD will call the tagtype() function

@copyright: (c) 2024 SynergyLabs
@license: CMU License. See License file for details.
"""

import json
import math
import requests
from flask import render_template, request, redirect, url_for, jsonify, session, flash
from flask_login import login_required
from uuid import uuid4
from werkzeug.security import generate_password_hash, gen_salt

from . import central
from .forms import *
from .utils import get_choices, get_tag_descendant_pairs
from .. import r
from ..auth.access_control import authorize_addition, permission, permission_allowed
from ..auth.acl_cache import invalidate_permission
from ..common import PAGE_SIZE
from ..models.cs_models import *
from ..oauth_bd.views import Client
from ..rest_api.helper import check_if_super, get_building_choices
from ..rest_api.helper import validate_users, form_query
from ..rpc import defs


@central.route("/tagtype", methods=["GET", "POST"])
@login_required
def tagtype():
    """Returns the list of TagTypes currently present in the system and adds a new
    type if the form is submitted and succesfully validated"""
    page = request.args.get("page", 1, type=int)
    skip_size = (page - 1) * PAGE_SIZE
    objs = TagType.objects().skip(skip_size).limit(PAGE_SIZE)
    # Can be deleted only if no child has a dependency on it
    for obj in objs:
        if (
            not obj.children
            and BuildingTemplate.objects(tag_types=obj.name).count()
            == 0
        ):
            obj.can_delete = True
        else:
            obj.can_delete = False
    form = TagTypeForm()
    form.parents.choices = get_choices(TagType)
    if form.validate_on_submit():
        # Create the tag
        payload = {
            "data": {
                "name": str(form.name.data),
                "description": str(form.description.data),
                "parents": [str(parent) for parent in form.parents.data],
                "acl_tag": check_if_super(session["email"]),
            }
        }
        res = requests.post(
            request.url_root + "api/tagtype",
            data=json.dumps(payload),
            headers=session["headers"],
        ).json()
        if res["success"] == "False":
            flash(res["error"])
        return redirect(url_for("central.tagtype"))
    return render_template("central/tagtype.html", objs=objs, form=form)


@central.route("/tagtype_delete", methods=["POST"])
@login_required
def tagtype_delete():
    """Deletes a tag"""
    name = request.form.get("name")
    res = requests.delete(
        request.url_root + "api/tagtype/" + name, headers=session["headers"]
    ).json()
    if res["success"] == "False":
        flash(res["error"])
    return redirect(url_for("central.tagtype"))


@central.route("/buildingtemplate", methods=["GET", "POST"])
@login_required
def buildingtemplate():
    """Create a buildingtemplate or retrieve the list of the current ones"""
    page = request.args.get("page", 1, type=int)
    skip_size = (page - 1) * PAGE_SIZE
    objs = BuildingTemplate.objects().skip(skip_size).limit(PAGE_SIZE)
    # If there are buildings using this template then mark as cannot be deleted
    for obj in objs:
        if Building.objects(template=obj.name).count() > 0:
            obj.can_delete = False
        else:
            obj.can_delete = True
        obj.tag_types = list(map(str, obj.tag_types))
    form = BuildingTemplateForm()
    # Get list of tags that this building can use
    form.tag_types.choices = get_choices(TagType)
    if form.validate_on_submit():
        payload = {
            "data": {
                "name": str(form.name.data),
                "description": str(form.description.data),
                "tag_types": form.tag_types.data,
            }
        }
        res = requests.post(
            request.url_root + "api/template",
            data=json.dumps(payload),
            headers=session["headers"],
        ).json()
        if res["success"] == "False":
            flash(res["error"])
        return redirect(url_for("central.buildingtemplate"))
    return render_template("central/buildingtemplate.html", objs=objs, form=form)


@central.route("/buildingtemplate_delete", methods=["POST"])
@login_required
def buildingtemplate_delete():
    name = request.form.get("name")
    res = requests.delete(
        request.url_root + "api/template/" + name, headers=session["headers"]
    ).json()
    if res["success"] == "False":
        flash(res["error"])
    return redirect(url_for("central.buildingtemplate"))


@central.route("/building", methods=["GET", "POST"])
@login_required
def building():
    """Create a new building or retrive the list of buildings currently in
    the system"""
    page = request.args.get("page", 1, type=int)
    skip_size = (page - 1) * PAGE_SIZE
    objs = Building.objects[skip_size : skip_size + PAGE_SIZE]
    # objs = Building.objects().skip(skip_size).limit(PAGE_SIZE)
    # If the building doesn't have any tags associated to it then mark
    # it as can be deleted
    for obj in objs:
        if len(obj.tags) == 0:
            obj.can_delete = True
        else:
            obj.can_delete = False
    form = BuildingForm()
    form.template.choices = get_choices(BuildingTemplate)
    if form.validate_on_submit():
        # Create the building
        payload = {
            "data": {
                "name": str(form.name.data),
                "description": str(form.description.data),
                "template": form.template.data,
            }
        }
        res = requests.post(
            request.url_root + "api/building",
            data=json.dumps(payload),
            headers=session["headers"],
        ).json()
        if res["success"] == "False":
            flash(res["error"])
        return redirect(url_for("central.building"))
    return render_template("central/building.html", objs=objs, form=form)


@central.route("/building_delete", methods=["POST"])
@login_required
def building_delete():
    name = request.form.get("name")
    res = requests.delete(
        request.url_root + "api/building/" + name, headers=session["headers"]
    ).json()
    if res["success"] == "False":
        flash(res["error"])
    return redirect(url_for("central.building"))


# api
@central.route("/building/<name>/metadata", methods=["GET", "POST"])
@login_required
def building_metadata(name):
    """If the request is a GET then retrieve the metadata associated with it. If it is a POST
    then update the metadata"""
    if request.method == "GET":
        metadata = Building._get_collection().find(
            {"name": name}, {"metadata": 1, "_id": 0}
        )[0]["metadata"]
        metadata = [{"name": key, "value": val} for key, val in list(metadata.items())]
        return jsonify({"data": metadata})
    else:
        # Update the metadata
        metadata = {pair["name"]: pair["value"] for pair in request.get_json()["data"]}
        Building.objects(name=name).update(set__metadata=metadata)
        return jsonify({"success": "True"})


@central.route("/building/<building_name>/tags", methods=["GET"])
@login_required
def building_tags(building_name):
    return render_template("central/buildingtags.html", building_name=building_name)


@central.route("/building/<building_name>/tags_delete", methods=["POST"])
@login_required
def building_tags_delete(building_name):
    """Delete specific tags associated with the building"""
    data = {
        "data": {
            "name": request.form.get("tag_name"),
            "value": request.form.get("tag_value"),
        }
    }
    res = requests.delete(
        request.url_root + "api/building/" + building_name + "/tags",
        data=json.dumps(data),
        headers=session["headers"],
    ).json()
    if res["success"] == "False":
        flash(res["error"])
    return redirect(url_for("central.building_tags", building_name=building_name))


@central.route("/user", methods=["GET"])
@login_required
def user():
    default = User.objects(role="default")
    super = User.objects(role="super")
    return render_template("central/user.html", super_user=super, default=default)


@central.route("/user/<email>/tags_owned", methods=["GET", "POST"])
@login_required
def user_tags_owned(email):
    """Retrieve or update the list of tags associated with this user"""
    if request.method == "GET":
        user = User.objects(email=email).first()
        buildings = user.buildings
        data = {}
        # Iterate over each building that this user is associated with and obtain the
        # building specific tags
        for building in buildings:
            tags = Building._get_collection().find(
                {"name": building}, {"tags.name": 1, "tags.value": 1, "_id": 0}
            )[0]["tags"]
            sub = {}
            for tag in tags:
                if tag["name"] in sub:
                    sub[tag["name"]].append(tag["value"])
                else:
                    sub[tag["name"]] = [tag["value"]]
            data[building] = sub
        # Form a list of dicts containing the building name and the tags which the user has for
        # that building
        triples = [
            {
                "building": item.building,
                "tags": [
                    {"name": elem.name, "value": elem.value} for elem in item.tags
                ],
            }
            for item in user.tags_owned
        ]
        print((triples, data))
        return jsonify({"data": data, "triples": triples})
    else:
        tags_owned = request.get_json()["data"]
        # Update the tags in MongoDB
        User.objects(email=email).update(set__tags_owned=tags_owned)

buildingdepot/CentralService/app/templates/central/building.html
{% extends "index.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuildingDepot - Building{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="page-header">
            <h2>Building <a href="#myModal" data-toggle="modal" class="btn btn-info btn-lg"><span
                    class="glyphicon glyphicon-hand-up"></span> Add a New Building</a></h2>
        </div>

        <div class="modal fade" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Add a New Building</h4>
                    </div>
                    <div class="modal-body">
                        {{ wtf.quick_form(form) }}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Template</th>
                    <th>Description</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in objs %}
                    <tr>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.template }}</td>
                        <td class="col-sm-4">{{ obj.description }}</td>
                        <td>
                            <form action="{{ url_for('central.building_tags', building_name=obj.name) }}">
                                <input type="submit" value="Tags" class="btn btn-success">
                            </form>
                        </td>
                        {% if obj.can_delete %}
                            <td>
                                <form action="{{ url_for('central.building_delete') }}" method="POST"
                                      onsubmit="return confirm('Are you sure you want to Delete?');">
                                    <input type="hidden" value="{{ obj.name }}" name="name">
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                </form>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        var app = angular.module("myApp", []);
        app.config(['$interpolateProvider', function ($interpolateProvider) {
            $interpolateProvider.startSymbol('{[');
            $interpolateProvider.endSymbol(']}');
        }]);
    </script>
{% endblock %}

buildingdepot/CentralService/app/templates/central/buildingtags.html
{% extends "index.html" %}

{% block title %}BuildingDepot - Building Tags{% endblock %}

{% block page_content %}
    <div class="row" ng-app="myApp" ng-controller="appController">
        <div class="page-header">
            <h2>Tags of Building {{ building_name }} <a ng-init="root.addNewTag()" href="#myModal" data-toggle="modal"
                                                        class="btn btn-info btn-lg"><span
                    class="glyphicon glyphicon-hand-up"></span> Add a New Building Tag</a></h2>
        </div>

        <div class="modal fade" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Add a New Building Tag</h4>
                    </div>
                    <div class="modal-body">

                        <form class="form-horizontal" ng-submit="root.submit()">
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Name</label>
                                <div class="col-lg-10">
                                    <select required class="form-control" ng-model="selectedName"
                                            ng-options="name for name in names"></select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Value</label>
                                <div class="col-lg-10">
                                    <input ng-model="value" required class="form-control" type="text">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Parents</label>
                                <div class="col-lg-10">
                                    <select multiple class="form-control" ng-model="selectedParents"
                                            ng-options="tag.value group by tag.name for tag in tags | optionFilter:this "></select>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-lg-12">
                                    <button class="btn btn-success pull-right" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

        <div>
            <div class="col-sm-2">
                <form class="form-vertical">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">Tag</label>
                        <select class="form-control" ng-model="selectedTag"
                                ng-options="tag.name+' '+tag.value group by tag.name for tag in tags">
                            <option value="">-- choose tag --</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label">SubTag</label>
                        <select class="form-control" ng-model="selectedSubTag"
                                ng-options="name for name in names | subTagFilter:this">
                            <option value="">-- choose subtag --</option>
                        </select>
                    </div>
                </form>
            </div>


            <div class="col-sm-10">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                        <th>Parents</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr ng-repeat="tag in tags | contentFilter:this | orderBy:['name', 'value']">
                        <td>{[ tag.name ]}</td>
                        <td>{[ tag.value ]}</td>
                        <td>
                            <p ng-repeat="parent in tag.parents">
                                {[ parent.name ]} {[ parent.value ]}
                            </p>
                        </td>
                        <td ng-show="tag.can_delete">
                            <form action="{{ url_for('central.building_tags_delete', building_name=building_name) }}"
                                  method="POST" onsubmit="return confirm('Are you sure you want to Delete?');">
                                <input type="hidden" value="{[ tag.name ]}" name="tag_name">
                                <input type="hidden" value="{[ tag.value ]}" name="tag_value">
                                <input type="submit" value="Delete" class="btn btn-danger">
                            </form>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        var app = angular.module("myApp", []);
        var header ={{ session.headers|tojson }};
        app.config(['$interpolateProvider', function ($interpolateProvider) {
            $interpolateProvider.startSymbol('{[');
            $interpolateProvider.endSymbol(']}');
        }]);
        app.controller("appController", function ($scope, $http) {
            $scope.root = {};
            $scope.selectedName = "";
            $scope.pairs = {};
            $scope.parent = [];
            $scope.root.addNewTag = function () {
                var res = $http.get('/api/building/' + '{{ building_name }}' + '/tags', {headers: header});
                res.success(function (data) {
                    if (data["success"] === "False") {
                        $.notify(data["error"], {
                            position: "top center",
                            clickToHide: true,
                            autoHideDelay: 4000
                        });
                    }
                    $scope.pairs = data.pairs;
                    $scope.tags = data.tags;

                    $scope.names = Object.keys($scope.pairs);
                });
                res.error(function () {
                    $.notify("Ajax failed", {position: "top center", clickToHide: true, autoHideDelay: 2000});
                });
            };
            $scope.root.submit = function () {
                if ($scope.selectedParents != undefined) {
                    $scope.temp = $scope.selectedParents;
                    for (var i = 0; i < $scope.temp.length; i++) {
                        delete $scope.temp[i].parents;
                        delete $scope.temp[i].can_delete;
                    }
                }
                var data = {
                    'name': $scope.selectedName,
                    'value': $scope.value,
                    'parents': $scope.selectedParents
                };
                for (var i = 0; i < $scope.tags.length; i++) {
                    if ($scope.tags[i].name === $scope.selectedName && $scope.tags[i].value === $scope.value) {
                        $.notify("There is already a tag with the same name and value", {
                            position: "top center",
                            clickToHide: true,
                            autoHideDelay: 2000
                        });
                        return;
                    }
                }
                var res = $http.post('/api/building/' + '{{ building_name }}' + '/tags', {'data': data}, {headers: header});
                res.success(function (data) {
                    if (data["success"] === "False") {
                        $.notify(data["error"], {
                            position: "top center",
                            clickToHide: true,
                            autoHideDelay: 4000
                        });
                    } else if (data["success"] === "True") {
                        $.notify("Success", {
                            globalPosition: 'top center',
                            clickToHide: true,
                            autoHideDelay: 2000,
                            className: 'success'
                        });
                        setTimeout(function () {
                            location.reload();
                        }, 335);
                    }
                });
                res.error(function () {
                    $.notify("Ajax failed", {position: "top center", clickToHide: true, autoHideDelay: 2000});
                });
            };
        });

        app.filter('optionFilter', [function () {
            return function (input, scope) {
                var parents = scope.pairs[scope.selectedName];
                return input.filter(function (elem) {
                    return parents.indexOf(elem.name) > -1;
                });
            };
        }]);

        app.filter('subTagFilter', [function () {
            return function (input, scope) {
                var selectedTag = scope.selectedTag;
                if (selectedTag !== null && selectedTag !== undefined) {
                    input = scope.graph[selectedTag.name];
                    return input.filter(function (elem) {
                        return scope.names.indexOf(elem) > -1;
                    });
                }
                return input;
            };
        }]);

        function isInvalid(obj) {
            return obj === null || obj === undefined;
        }

        app.filter('contentFilter', [function () {
            return function (input, scope) {
                var selectedTag = scope.selectedTag;
                var selectedSubTag = scope.selectedSubTag;
                if (isInvalid(selectedTag)) {
                    if (isInvalid(selectedSubTag)) {
                        return input;
                    }
                    return input.filter(function (elem) {
                        return elem.name === selectedSubTag;
                    });
                } else {
                    if (isInvalid(selectedSubTag)) {
                        return [selectedTag];
                    }
                    var ancestor = selectedTag.name + selectedTag.value;
                    return input.filter(function (elem) {
                        return elem.name === selectedSubTag && elem.ancestors.indexOf(ancestor) > -1;
                    });
                }
            };
        }]);
    </script>
{% endblock %}

buildingdepot/CentralService/app/templates/central/query.html
{% extends "index.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuildingDepot - Permission Query{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="page-header">
            <h2>Permission Query</h2>
            <div class="col-sm-4">
                {{ wtf.quick_form(form) }}
                {% if res %}
                    <h3>Permission: {{ res }}</h3>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

buildingdepot/CentralService/app/templates/central/tagtype.html
{% extends "index.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuildingDepot - TagType{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="page-header">
            <h2>TagType <a href="#myModal" data-toggle="modal" class="btn btn-info btn-lg"><span
                    class="glyphicon glyphicon-hand-up"></span> Add a New TagType</a></h2>
        </div>

        <div class="modal fade" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Add a New TagType</h4>
                    </div>
                    <div class="modal-body">
                        {{ wtf.quick_form(form) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Parents</th>
                    <th>Children</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in objs %}
                    <tr>
                        <td>{{ obj.name }}</td>
                        <td class="col-sm-4">
                            {{ obj.description }}
                        </td>
                        <td>
                            <select multiple disabled class="form-control">
                                {% for parent in obj.parents %}
                                    <option>{{ parent }}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td>
                            <select multiple disabled class="form-control">
                                {% for child in obj.children %}
                                    <option>{{ child }}</option>
                                {% endfor %}
                            </select>
                        </td>
                        {% if obj.can_delete %}
                            <td>
                                <form action="{{ url_for('central.tagtype_delete') }}" method="POST"
                                      onsubmit="return confirm('Are you sure you want to Delete?');">
                                    <input type="hidden" value="{{ obj.name }}" name="name">
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                </form>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
{% endblock %}